apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: db-copier
    labels:
      app: db-copier
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: db-copier
      deploymentconfig: db-copier
    strategy:
      activeDeadlineSeconds: 21600
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: db-copier
          deploymentconfig: db-copier
      spec:
        restartPolicy: Never
        containers:
        - env:
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                key: database-readonly-host
                name: advisor-db
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: advisor-db
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: advisor-db
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: advisor-db
          image: postgres:10.6
          imagePullPolicy: Always
          name: db-copier
          command: ["/bin/sh", "-c", "tail -f /dev/null"]
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: {}
