scrape_configs:
  - job_name: 'advisor-api'
    scrape_interval: 15s
    # metrics_path is the URL endpoint, not the directory containing prometheus metric files
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.containers.internal:8000'
        labels:
          service: 'advisor-backend-api'

  - job_name: 'advisor-service'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.containers.internal:8001'
        labels:
          service: 'advisor-backend-service'
