from ..cimpl import CONFIG_SOURCE_DEFAULT_CONFIG as CONFIG_SOURCE_DEFAULT_CONFIG, CONFIG_SOURCE_DYNAMIC_BROKER_CONFIG as CONFIG_SOURCE_DYNAMIC_BROKER_CONFIG, CONFIG_SOURCE_DYNAMIC_DEFAULT_BROKER_CONFIG as CONFIG_SOURCE_DYNAMIC_DEFAULT_BROKER_CONFIG, CONFIG_SOURCE_DYNAMIC_TOPIC_CONFIG as CONFIG_SOURCE_DYNAMIC_TOPIC_CONFIG, CONFIG_SOURCE_GROUP_CONFIG as CONFIG_SOURCE_GROUP_CONFIG, CONFIG_SOURCE_STATIC_BROKER_CONFIG as CONFIG_SOURCE_STATIC_BROKER_CONFIG, CONFIG_SOURCE_UNKNOWN_CONFIG as CONFIG_SOURCE_UNKNOWN_CONFIG, NewPartitions as NewPartitions, NewTopic as NewTopic, RESOURCE_ANY as RESOURCE_ANY, RESOURCE_BROKER as RESOURCE_BROKER, RESOURCE_GROUP as RESOURCE_GROUP, RESOURCE_TOPIC as RESOURCE_TOPIC, RESOURCE_TRANSACTIONAL_ID as RESOURCE_TRANSACTIONAL_ID, RESOURCE_UNKNOWN as RESOURCE_UNKNOWN, _AdminClientImpl
from ._acl import AclBinding as AclBinding, AclBindingFilter as AclBindingFilter, AclOperation as AclOperation, AclPermissionType as AclPermissionType
from ._cluster import DescribeClusterResult as DescribeClusterResult
from ._config import AlterConfigOpType as AlterConfigOpType, ConfigEntry as ConfigEntry, ConfigResource as ConfigResource, ConfigSource as ConfigSource
from ._group import ConsumerGroupDescription as ConsumerGroupDescription, ConsumerGroupListing as ConsumerGroupListing, ListConsumerGroupsResult as ListConsumerGroupsResult, MemberAssignment as MemberAssignment, MemberDescription as MemberDescription
from ._listoffsets import ListOffsetsResultInfo as ListOffsetsResultInfo, OffsetSpec as OffsetSpec
from ._metadata import BrokerMetadata as BrokerMetadata, ClusterMetadata as ClusterMetadata, GroupMember as GroupMember, GroupMetadata as GroupMetadata, PartitionMetadata as PartitionMetadata, TopicMetadata as TopicMetadata
from ._records import DeletedRecords as DeletedRecords
from ._resource import ResourcePatternType as ResourcePatternType, ResourceType as ResourceType
from ._scram import ScramCredentialInfo as ScramCredentialInfo, ScramMechanism as ScramMechanism, UserScramCredentialAlteration as UserScramCredentialAlteration, UserScramCredentialDeletion as UserScramCredentialDeletion, UserScramCredentialUpsertion as UserScramCredentialUpsertion, UserScramCredentialsDescription as UserScramCredentialsDescription
from ._topic import TopicDescription as TopicDescription

string_type = basestring
string_type = str

class AdminClient(_AdminClientImpl):
    def __init__(self, conf, **kwargs) -> None: ...
    def create_topics(self, new_topics, **kwargs): ...
    def delete_topics(self, topics, **kwargs): ...
    def list_topics(self, *args, **kwargs): ...
    def list_groups(self, *args, **kwargs): ...
    def create_partitions(self, new_partitions, **kwargs): ...
    def describe_configs(self, resources, **kwargs): ...
    def alter_configs(self, resources, **kwargs): ...
    def incremental_alter_configs(self, resources, **kwargs): ...
    def create_acls(self, acls, **kwargs): ...
    def describe_acls(self, acl_binding_filter, **kwargs): ...
    def delete_acls(self, acl_binding_filters, **kwargs): ...
    def list_consumer_groups(self, **kwargs): ...
    def describe_consumer_groups(self, group_ids, **kwargs): ...
    def describe_topics(self, topics, **kwargs): ...
    def describe_cluster(self, **kwargs): ...
    def delete_consumer_groups(self, group_ids, **kwargs): ...
    def list_consumer_group_offsets(self, list_consumer_group_offsets_request, **kwargs): ...
    def alter_consumer_group_offsets(self, alter_consumer_group_offsets_request, **kwargs): ...
    def set_sasl_credentials(self, username, password) -> None: ...
    def describe_user_scram_credentials(self, users=None, **kwargs): ...
    def alter_user_scram_credentials(self, alterations, **kwargs): ...
    def list_offsets(self, topic_partition_offsets, **kwargs): ...
    def delete_records(self, topic_partition_offsets, **kwargs): ...
    def elect_leaders(self, election_type, partitions=None, **kwargs): ...
