from .._util import ConversionUtil as ConversionUtil, ValidationUtil as ValidationUtil
from ._resource import ResourcePatternType as ResourcePatternType, ResourceType as ResourceType
from _typeshed import Incomplete
from enum import Enum

string_type = basestring
string_type = str

class AclOperation(Enum):
    UNKNOWN = ...
    ANY = ...
    ALL = ...
    READ = ...
    WRITE = ...
    CREATE = ...
    DELETE = ...
    ALTER = ...
    DESCRIBE = ...
    CLUSTER_ACTION = ...
    DESCRIBE_CONFIGS = ...
    ALTER_CONFIGS = ...
    IDEMPOTENT_WRITE = ...
    def __lt__(self, other): ...

class AclPermissionType(Enum):
    UNKNOWN = ...
    ANY = ...
    DENY = ...
    ALLOW = ...
    def __lt__(self, other): ...

class AclBinding:
    restype: Incomplete
    name: Incomplete
    resource_pattern_type: Incomplete
    principal: Incomplete
    host: Incomplete
    operation: Incomplete
    permission_type: Incomplete
    restype_int: Incomplete
    resource_pattern_type_int: Incomplete
    operation_int: Incomplete
    permission_type_int: Incomplete
    def __init__(self, restype, name, resource_pattern_type, principal, host, operation, permission_type) -> None: ...
    def __hash__(self): ...
    def __lt__(self, other): ...
    def __eq__(self, other): ...

class AclBindingFilter(AclBinding): ...
