from ._resource import ResourceType as ResourceType
from _typeshed import Incomplete
from enum import Enum

class AlterConfigOpType(Enum):
    SET = ...
    DELETE = ...
    APPEND = ...
    SUBTRACT = ...

class ConfigSource(Enum):
    UNKNOWN_CONFIG = ...
    DYNAMIC_TOPIC_CONFIG = ...
    DYNAMIC_BROKER_CONFIG = ...
    DYNAMIC_DEFAULT_BROKER_CONFIG = ...
    STATIC_BROKER_CONFIG = ...
    DEFAULT_CONFIG = ...
    GROUP_CONFIG = ...

class ConfigEntry:
    name: Incomplete
    value: Incomplete
    source: Incomplete
    is_read_only: Incomplete
    is_default: Incomplete
    is_sensitive: Incomplete
    is_synonym: Incomplete
    synonyms: Incomplete
    incremental_operation: Incomplete
    def __init__(self, name, value, source=..., is_read_only: bool = False, is_default: bool = False, is_sensitive: bool = False, is_synonym: bool = False, synonyms=[], incremental_operation=None) -> None: ...

class ConfigResource:
    Type = ResourceType
    restype: Incomplete
    restype_int: Incomplete
    name: Incomplete
    set_config_dict: Incomplete
    incremental_configs: Incomplete
    configs: Incomplete
    error: Incomplete
    def __init__(self, restype, name, set_config=None, described_configs=None, error=None, incremental_configs=None) -> None: ...
    def __hash__(self): ...
    def __lt__(self, other): ...
    def __eq__(self, other): ...
    def __len__(self) -> int: ...
    def set_config(self, name, value, overwrite: bool = True) -> None: ...
    def add_incremental_config(self, config_entry) -> None: ...
