import abc
from .. import cimpl as cimpl
from _typeshed import Incomplete
from abc import ABC

class OffsetSpec(ABC, metaclass=abc.ABCMeta):
    @classmethod
    def earliest(cls): ...
    @classmethod
    def latest(cls): ...
    @classmethod
    def max_timestamp(cls): ...
    @classmethod
    def for_timestamp(cls, timestamp): ...
    def __new__(cls, index): ...
    def __lt__(self, other): ...

class TimestampSpec(OffsetSpec):
    def __new__(cls, _): ...
    timestamp: Incomplete
    def __init__(self, timestamp) -> None: ...

class MaxTimestampSpec(OffsetSpec):
    def __new__(cls): ...

class LatestSpec(OffsetSpec):
    def __new__(cls): ...

class EarliestSpec(OffsetSpec):
    def __new__(cls): ...

class ListOffsetsResultInfo:
    offset: Incomplete
    timestamp: Incomplete
    leader_epoch: Incomplete
    def __init__(self, offset, timestamp, leader_epoch) -> None: ...
