# Generated by Django 6.0.5 on 2026-06-01 23:29

import django.contrib.postgres.fields
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0045_remove_dailyhitgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorInventoryHost',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('account', models.CharField(blank=True, max_length=10, null=True)),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('display_name', models.CharField(max_length=200)),
                ('tags', models.JSONField()),
                ('workspace_id', models.UUIDField(null=True)),
                ('workspace_name', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('last_check_in', models.DateTimeField()),
                ('stale_timestamp', models.DateTimeField()),
                ('insights_id', models.UUIDField()),
                ('reporter', models.CharField(default='puptoo', max_length=200)),
                ('per_reporter_staleness', models.JSONField(default=dict)),
                ('os_name', models.CharField(blank=True, max_length=50, null=True)),
                ('os_major', models.IntegerField(null=True)),
                ('os_minor', models.IntegerField(null=True)),
                ('host_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bootc_booted_image', models.CharField(blank=True, max_length=512, null=True)),
                ('bootc_booted_image_digest', models.CharField(blank=True, max_length=256, null=True)),
                ('owner_id', models.UUIDField(null=True)),
                ('rhc_client_id', models.UUIDField(null=True)),
                ('sap_system', models.BooleanField(null=True)),
                ('sap_sids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list)),
                ('ansible', models.JSONField(null=True)),
                ('mssql', models.JSONField(null=True)),
                ('system_update_method', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('advisorinventoryhost'), models.Model),
        ),
    ]
