# Generated by Django 6.0.5 on 2026-07-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_advisor_inventory_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorinventoryhost',
            name='workspace_ungrouped',
            field=models.BooleanField(null=True),
        ),
    ]
