# Copyright 2016-2024 the Advisor Backend team at Red Hat.
# This file is part of the Insights Advisor project.

# Insights Advisor is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.

# Insights Advisor is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with Insights Advisor. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.1.2 on 2020-10-20 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0012_field_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(max_length=10)),
                ('branch_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('suggestion', models.CharField(choices=[('P', 'proposed'), ('A', 'accepted'), ('R', 'rejected')], max_length=1, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=80, null=True)),
                ('silenced', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('allow_reboot', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatMaintenanceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.host')),
                ('plan', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='sat_compat.satmaintenance')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rule')),
                ('playbook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.playbook')),
            ],
        ),
    ]
