# Copyright 2016-2024 the Advisor Backend team at Red Hat.
# This file is part of the Insights Advisor project.

# Insights Advisor is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.

# Insights Advisor is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with Insights Advisor. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.1.4 on 2021-04-22 01:03

from django.db import migrations, models
import django.db.models.deletion


def delete_actions_with_no_system(apps, schema_editor):
    """
    When this comes online in Production we should have no plans for any
    account, and if we've imported them from Classic they should all have a
    system anyway.  So it's safe to delete those actions that do not have a
    system.
    """
    SatMaintenanceAction = apps.get_model('sat_compat', 'SatMaintenanceAction')
    SatMaintenanceAction.objects.filter(host_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210329_1403'),
        ('sat_compat', '0001_maintenance_models'),
    ]

    operations = [
        migrations.RunPython(
            delete_actions_with_no_system, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='satmaintenanceaction',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.host'),
        ),
    ]
