from ..cimpl import KafkaError as KafkaError

string_type = basestring
string_type = str

class ValidationUtil:
    @staticmethod
    def check_multiple_not_none(obj, vars_to_check) -> None: ...
    @staticmethod
    def check_not_none(obj, param) -> None: ...
    @staticmethod
    def check_multiple_is_string(obj, vars_to_check) -> None: ...
    @staticmethod
    def check_is_string(obj, param) -> None: ...
    @staticmethod
    def check_kafka_errors(errors) -> None: ...
    @staticmethod
    def check_kafka_error(error) -> None: ...
