from .error import ConsumeError as ConsumeError, KeyDeserializationError as KeyDeserializationError, ValueDeserializationError as ValueDeserializationError
from .serialization import MessageField as MessageField, SerializationContext as SerializationContext
from confluent_kafka.cimpl import Consumer as _ConsumerImpl

class DeserializingConsumer(_ConsumerImpl):
    def __init__(self, conf) -> None: ...
    def poll(self, timeout: int = -1): ...
    def consume(self, num_messages: int = 1, timeout: int = -1) -> None: ...
