from _typeshed import Incomplete
from enum import Enum

class Node:
    id: Incomplete
    id_string: Incomplete
    host: Incomplete
    port: Incomplete
    rack: Incomplete
    def __init__(self, id, host, port, rack=None) -> None: ...

class ConsumerGroupTopicPartitions:
    group_id: Incomplete
    topic_partitions: Incomplete
    def __init__(self, group_id, topic_partitions=None) -> None: ...

class ConsumerGroupState(Enum):
    UNKNOWN = ...
    UNKOWN = UNKNOWN
    PREPARING_REBALANCING = ...
    COMPLETING_REBALANCING = ...
    STABLE = ...
    DEAD = ...
    EMPTY = ...
    def __lt__(self, other): ...

class ConsumerGroupType(Enum):
    UNKNOWN = ...
    CONSUMER = ...
    CLASSIC = ...
    def __lt__(self, other): ...

class TopicCollection:
    topic_names: Incomplete
    def __init__(self, topic_names) -> None: ...

class TopicPartitionInfo:
    id: Incomplete
    leader: Incomplete
    replicas: Incomplete
    isr: Incomplete
    def __init__(self, id, leader, replicas, isr) -> None: ...

class IsolationLevel(Enum):
    READ_UNCOMMITTED = ...
    READ_COMMITTED = ...
    def __lt__(self, other): ...

class ElectionType(Enum):
    PREFERRED = ...
    UNCLEAN = ...
    def __lt__(self, other): ...
