from _typeshed import Incomplete
from confluent_kafka import Consumer as Consumer, KafkaError as KafkaError, KafkaException as KafkaException
from verifiable_client import VerifiableClient

class VerifiableConsumer(VerifiableClient):
    consumer: Incomplete
    consumed_msgs: int
    consumed_msgs_last_reported: int
    consumed_msgs_at_last_commit: int
    use_auto_commit: bool
    use_async_commit: bool
    max_msgs: int
    assignment: Incomplete
    assignment_dict: Incomplete
    def __init__(self, conf) -> None: ...
    def find_assignment(self, topic, partition): ...
    def send_records_consumed(self, immediate: bool = False) -> None: ...
    def send_assignment(self, evtype, partitions) -> None: ...
    def on_assign(self, consumer, partitions) -> None: ...
    def on_revoke(self, consumer, partitions) -> None: ...
    def on_commit(self, err, partitions) -> None: ...
    def do_commit(self, immediate: bool = False, asynchronous=None) -> None: ...
    def msg_consume(self, msg) -> None: ...

class AssignedPartition:
    topic: Incomplete
    partition: Incomplete
    skey: Incomplete
    consumed_msgs: int
    min_offset: int
    max_offset: int
    def __init__(self, topic, partition) -> None: ...
    def to_dict(self): ...
