from _typeshed import Incomplete

class VerifiableClient:
    conf: Incomplete
    run: bool
    def __init__(self, conf) -> None: ...
    def sig_term(self, sig, frame) -> None: ...
    def dbg(self, s) -> None: ...
    def err(self, s, term: bool = False) -> None: ...
    def send(self, d) -> None: ...
    @staticmethod
    def set_config(conf, args): ...
    @staticmethod
    def read_config_file(path): ...
