# Copyright 2016-2024 the Advisor Backend team at Red Hat.
# This file is part of the Insights Advisor project.

# Insights Advisor is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.

# Insights Advisor is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with Insights Advisor. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 4.0.3 on 2022-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_tasks_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteRhc',
            fields=[
                ('instance_id', models.UUIDField(primary_key=True, serialize=False)),
                ('source_id', models.BigIntegerField(unique=True)),
                ('rhc_client_id', models.UUIDField(db_index=True, null=True)),
            ],
        ),
    ]
