# Copyright 2016-2024 the Advisor Backend team at Red Hat.
# This file is part of the Insights Advisor project.

# Insights Advisor is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.

# Insights Advisor is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with Insights Advisor. If not, see <https://www.gnu.org/licenses/>.

# Generated by copy, paste and mangling
import uuid

from django.db import migrations, models


def generate_tokens_for_existing_executed_tasks(apps, schema_editor):
    ExecutedTask = apps.get_model('tasks', 'ExecutedTask')
    # We don't want to hammer the database doing individual updates for
    # potentially thousands of rows.  So we generate our own set of tokens,
    # and then bulk update those.
    extasks = []
    for extask in ExecutedTask.objects.all():
        if extask.token is not None:
            # Allow for a partial migration state ... just in case...
            continue
        extask.token = uuid.uuid4()
        extasks.append(extask)
    # Finally do the update, in reasonable batches
    ExecutedTask.objects.bulk_update(extasks, ['token'], batch_size=100)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tasks_add_parameters'),
    ]

    # Have to start with a null field, generate the tokens for all the
    # existing executed tasks, and then set it unique and not null.
    operations = [
        migrations.AddField(
            model_name='executedtask',
            name='token',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            generate_tokens_for_existing_executed_tasks,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='executedtask',
            name='token',
            field=models.UUIDField(null=False, default=uuid.uuid4, unique=True),
        )
    ]
