# Copyright 2016-2024 the Advisor Backend team at Red Hat.
# This file is part of the Insights Advisor project.

# Insights Advisor is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.

# Insights Advisor is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with Insights Advisor. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 4.1.13 on 2024-03-27 22:39

# from django.contrib.postgres.aggregates import ArrayAgg
from django.db import migrations, models

from tasks.models import ExecutedTaskStatusChoices


class OldExecutedTaskStatusChoices(models.IntegerChoices):
    RUNNING = 1
    COMPLETED = 2
    FAILURE = 3
    CANCELLED = 4


def add_completed_with_errors(apps, schema_editor):
    """
    The only number that needs to change is Cancelled
    """
    ExecutedTask = apps.get_model('tasks', 'ExecutedTask')
    ExecutedTask.objects.filter(
        status=OldExecutedTaskStatusChoices.CANCELLED
    ).update(status=ExecutedTaskStatusChoices.CANCELLED)


def remove_completed_with_errors(apps, schema_editor):
    """
    The only number that needs to change is Cancelled
    """
    ExecutedTask = apps.get_model('tasks', 'ExecutedTask')
    ExecutedTask.objects.filter(
        status=ExecutedTaskStatusChoices.CANCELLED
    ).update(status=OldExecutedTaskStatusChoices.CANCELLED)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_type_bash_to_script'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executedtaskparameter',
            options={'ordering': ['parameter__key']},
        ),
        migrations.AlterField(
            model_name='executedtask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Running'), (2, 'Completed'), (3, 'Completed With Errors'), (4, 'Failure'), (5, 'Cancelled')]),
        ),
        migrations.RunPython(add_completed_with_errors, remove_completed_with_errors),
    ]
