# Copyright 2016-2024 the Advisor Backend team at Red Hat.
# This file is part of the Insights Advisor project.

# Insights Advisor is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.

# Insights Advisor is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with Insights Advisor. If not, see <https://www.gnu.org/licenses/>.

# Generated by Paul Wayper from pure inventium

from django.db import migrations


def delete_empty_executed_tasks(apps, schema_editor):
    ExecutedTask = apps.get_model('tasks', 'ExecutedTask')
    ExecutedTask.objects.filter(job__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_job_rhc_client_id'),
    ]

    operations = [
        migrations.RunPython(delete_empty_executed_tasks, migrations.RunPython.noop),
    ]
