# Copyright 2016-2024 the Advisor Backend team at Red Hat.
# This file is part of the Insights Advisor project.

# Insights Advisor is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.

# Insights Advisor is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with Insights Advisor. If not, see <https://www.gnu.org/licenses/>.

# Generated by Paul using the powers of copy and paste

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


def set_values_default(apps, schema_editor):
    """
    Set up a harmless default values list
    """
    TaskParameter = apps.get_model('tasks', 'TaskParameter')
    for param in TaskParameter.objects.all():
        param.values = [param.default or 'default']
        param.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_delete_empty_executed_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskparameter',
            name='values',
            field=ArrayField(base_field=models.CharField(max_length=250), null=True),
        ),
        migrations.RunPython(
            set_values_default, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='taskparameter',
            name='values',
            field=ArrayField(base_field=models.CharField(max_length=250)),
        ),
    ]
