# Copyright 2016-2024 the Advisor Backend team at Red Hat.
# This file is part of the Insights Advisor project.

# Insights Advisor is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.

# Insights Advisor is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with Insights Advisor. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 4.2.11 on 2024-07-10 13:57

from django.db import migrations, models


def assign_unique_indexes_to_all_parameters(apps, schema_editor):
    TaskParameter = apps.get_model('tasks', 'TaskParameter')
    # Just assign the ID as the index, because that's unique.  Any fixtures
    # applied later can change the index.
    TaskParameter.objects.update(index=models.F('id'))


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_taskparameter_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskparameter',
            name='index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(
            assign_unique_indexes_to_all_parameters, migrations.RunPython.noop
        ),
        migrations.AlterModelOptions(
            name='executedtaskparameter',
            options={'ordering': ['parameter__index']},
        ),
        migrations.AlterModelOptions(
            name='taskparameter',
            options={'ordering': ['index']},
        ),
        migrations.AddConstraint(
            model_name='taskparameter',
            constraint=models.UniqueConstraint(fields=('task', 'index'), name='taskparameter_task_index_uniqueness'),
        ),
    ]
