import io
from .schema_registry_client import AsyncSchemaRegistryClient as AsyncSchemaRegistryClient, ConfigCompatibilityLevel as ConfigCompatibilityLevel, Metadata as Metadata, MetadataProperties as MetadataProperties, MetadataTags as MetadataTags, RegisteredSchema as RegisteredSchema, Rule as Rule, RuleKind as RuleKind, RuleMode as RuleMode, RuleParams as RuleParams, RuleSet as RuleSet, Schema as Schema, SchemaReference as SchemaReference, SchemaRegistryClient as SchemaRegistryClient, SchemaRegistryError as SchemaRegistryError, ServerConfig as ServerConfig

__all__ = ['ConfigCompatibilityLevel', 'Metadata', 'MetadataProperties', 'MetadataTags', 'RegisteredSchema', 'Rule', 'RuleKind', 'RuleMode', 'RuleParams', 'RuleSet', 'Schema', 'SchemaRegistryClient', 'AsyncSchemaRegistryClient', 'SchemaRegistryError', 'SchemaReference', 'ServerConfig', 'topic_subject_name_strategy', 'topic_record_subject_name_strategy', 'record_subject_name_strategy', 'header_schema_id_serializer', 'prefix_schema_id_serializer', 'dual_schema_id_deserializer', 'prefix_schema_id_deserializer']

def topic_subject_name_strategy(ctx, record_name: str | None) -> str | None: ...
def topic_record_subject_name_strategy(ctx, record_name: str | None) -> str | None: ...
def record_subject_name_strategy(ctx, record_name: str | None) -> str | None: ...
def header_schema_id_serializer(payload: bytes, ctx, schema_id) -> bytes: ...
def prefix_schema_id_serializer(payload: bytes, ctx, schema_id) -> bytes: ...
def dual_schema_id_deserializer(payload: bytes, ctx, schema_id) -> io.BytesIO: ...
def prefix_schema_id_deserializer(payload: bytes, ctx, schema_id) -> io.BytesIO: ...
